baseURL = 'https://alpfree.github.io/'
languageCode = 'en-us'
title = 'AlphaFree'
theme = 'hugo-PaperMod'

[params.homeInfoParams]
  Title = "ğŸ‘‹ æ¬¢è¿æ¥åˆ° AlphaFreeï¼"
  Content = """
ğŸ“ˆ å…³æ³¨é¢†åŸŸï¼šç§‘æŠ€ã€é‡‘èï¼Œ**æä¾›æœ‰ä»·å€¼ä¿¡æ¯**ï¼›ç¬”è€…ï¼šè¯åˆ¸åˆ†æå¸ˆã€è½¯ä»¶è®¾è®¡å¸ˆã€ä¼šè®¡å¸ˆ  
ğŸ“± è·å–æœ€æ–°æ–‡ç« ï¼Œè¯·å…³æ³¨å¾®ä¿¡å…¬ä¼—å·ï¼š**AlphaFree**
"""

[minify]
  disableJSON = true

[params.analytics.google]
  # Google Analytics 4 Measurement ID
  GA4 = "G-KGCGBXF5P6" 
  
