baseURL = 'https://alpfree.github.io/'
languageCode = 'en-us'
title = 'AlphaFree'
theme = 'hugo-PaperMod'

[params.homeInfoParams]
  Title = "ğŸ‘‹ æ¬¢è¿æ¥åˆ° AlphaFreeï¼"
  Content = """
å…³æ³¨é¢†åŸŸï¼šç§‘æŠ€ã€é‡‘èï¼Œæä¾›æœ‰ä»·å€¼ä¿¡æ¯ï¼›ç¬”è€…ï¼šè¯åˆ¸åˆ†æå¸ˆã€è½¯ä»¶è®¾è®¡å¸ˆã€ä¼šè®¡å¸ˆï¼›å¾®ä¿¡å…¬ä¼—å·ï¼šAlphaFree
"""
